apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nodeappds
  labels: 
    app: nodeapp
spec:
  selector:  # replicas will not come in daemonset
    matchLabels:
      app: nodeapp
  template:
    metadata:
      name: nodeapppod
      labels:
        app: nodeapp
    spec:
      containers:
      - name: nodeappcontainer
        image: dockerhandson/nodeapp:1
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: nodeappsvc
spec:
  selector:
    app: nodeapp
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 32102
  type: NodePort                      