apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebappdeployment
  labels:
    app: javawebapp
spec:
  replicas: 3
  strategy:    # changes will be occure fordeployment (strategy,type)
    type: Recreate
  selector:
    matchLabels:
      app: javawebapp
  template:
    metadata:
      name: javawebapppod
      labels:
        app: javawebapp
    spec:
      containers:
      - name: javawebappcontainer
        image: dockerhandson/java-web-app:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: deservice
spec:
  selector:
    app: javawebapp
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 32555